# Generated by Django 3.2.5 on 2021-07-22 03:07

from django.db import migrations
import webusers.models


class Migration(migrations.Migration):

    dependencies = [
        ('webusers', '0002_auto_20210716_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuário'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', webusers.models.CustomUserManager()),
            ],
        ),
    ]
